### ISSUE TITLE
Syntax highlighting is the same color as the preformatted background color

### ISSUE THREAD

**Issue by bigbass1997** [KevinWorkman/HappyCoding#1]
On any pages that use the code syntax highlighting, nearly all of the code is colored white, which is the same as the background color of the `<pre>` (preformated) block.

Example Image: [http://i.imgur.com/kxgD1Qs.png](http://i.imgur.com/kxgD1Qs.png)
Here I have part of the first line "selected" to confirm that the text is shown, but it is in the same color as the background.

From what I can tell from my browser's html/css inspection tools, it seems that the ".highlight" class from both syntax-light.css and syntax-dark.css are being loaded, and the class from the syntax-light.css is being used. The "theme/color" switcher button does change the css links in the page header, but it appears the code being used to disable one set or the other is not correct.

`<link disabled="disabled" rel="stylesheet" type="text/css" href="/css/syntax-light.css" class="light-css">`

According to [http://www.w3schools.com/jsref/prop_link_disabled.asp](http://www.w3schools.com/jsref/prop_link_disabled.asp), the value supposed to be used for the "disabled" attribute is either true or false, not the actual word "disabled".

I could be wrong about the cause, but the problem certainly exists. Testing will need to be done to be sure.

**Comment by KevinWorkman** [comment]
Thanks for the bug report! What browser are you using?

Also, see the little half-circle button in the upper-right corner? That's meant to switch the theme. Does the syntax fix itself after you click it?

**Comment by bigbass1997** [comment]
Hmm now this is strange. I decided to try a different browser.

The browser I currently use is called Waterfox, it is basically Firefox but designed for 64bit machines.

I tried Chrome, and that did properly disable the needed css links in the header tag block. So it appears to be a browser issue I guess.

**Comment by bigbass1997** [comment]
> Does the syntax fix itself after you click it?
> 
> The "theme/color" switcher button does change the css links in the page header, but it appears the code being used to disable one set or the other is not correct.

In other words, no pressing that does not fix the issue.

And it appears now that the website code is correct I guess?

**Comment by KevinWorkman** [comment]
Okay I downloaded WaterFox, and I see the issue now. It works in chrome, firefox, and IE, gotta love browser compatibility problems!

This is super helpful, thanks a lot. I'll poke around and hopefully fix it tonight or tomorrow!

**Comment by bigbass1997** [comment]
That is just so strange! I have never experienced a css/html compatibility difference between Firefox and Waterfox.. I'll try doing some research and see if anyone else has found this problem before. Also look into seeing of my browser needs updating.

**Comment by bigbass1997** [comment]
Alright so with Chrome, no matter what the disabled attribute is set to equal, it still disables the link tag, even just `<link rel="stylesheet" type="text/css" href="/css/syntax-light.css" class="light-css" disabled>` appears to work.

I tried updating Waterfox, problem still persists. I could not find anyone reporting a similar issue online or on the [Waterfox Github](https://github.com/MrAlex94/Waterfox).

I can however confirm the problem is not isolated to your website. I tested css linking on my site, and the problem persists there too. (and continues to work on Chrome)

**Comment by KevinWorkman** [comment]
[This page](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link) offers a hint:

> The use of disabled as an HTML attribute is non-standard and only used by some browsers (W3 #27677). Do not use it. To achieve a similar effect, use one of the following techniques:
> - If the disabled attribute has been added directly to the element on the page, do not include the <link> element instead;
> - Set the disabled property of the StyleSheet DOM object via scripting.

I've started using the property instead of the attribute, and it seems to mostly work.

One more small issue remains broken: the GitHub link in the upper-right is also supposed to change color. That works in other browsers, but not Waterfox. I'll keep poking around.

**Comment by bigbass1997** [comment]
> One more small issue remains broken: the GitHub link in the upper-right is also supposed to change color.

That's a bit harder for me to test without running your site locally, which I do not know how to do. If you refresh the page after setting the theme to dark, the icon's color still hasn't changed as it should. And as far as I can tell, the CSS is changing now as it should.

It seems as though the icon just decides to ignore the CSS on Waterfox, maybe? Everything changes color as it should, including the "change theme" button/icon, and even the browser tab icon, except the Github icon..

**Comment by bigbass1997** [comment]
Think I figured out the problem: [StackOverflow](http://stackoverflow.com/questions/12262118/content-url-is-not-working-in-firefox)

**Comment by bigbass1997** [comment]
Found working solution, just haven't looked at exactly how to implement it into your site, but here is a working example: [JSFiddle](https://jsfiddle.net/0byff6pb/)

`true` in the if statement, sets the img src attribute to the white/light image, `false` leaves it as the black/dark image.

Tested locally, works on both Chrome and Waterfox. (put it on JSFiddle for ease of giving you the code I used)

**Comment by KevinWorkman** [comment]
Okay cool, that looks very promising.

Right now I'm doing it via css. In `/js/main.js` I have a function called `doThemeCss()` that switches the css files. Then in `/css/main-dark.css` and `/css/main-light.css` I set the content of the `github-img`.

I think to try out your solution, all it would take is adding two lines to `main.js` inside the `if` statement in the `doThemeCss()` function:

If the theme is dark then do: `$("#github-img").attr("src", "/images/GitHub-Mark-Light-32px.png");`
If it's light, then do: `$("#github-img").attr("src", "/images/GitHub-Mark-32px.png`);`

I won't be able to get to this until later today, but if you want to make a pull request, I'd love for you to get credit for figuring all this stuff out (and taking the time to make a bug report!). If you don't feel like all that, then that's cool too, this should be very easy to test on my end. Completely up to you!

**Comment by bigbass1997** [comment]
All issues mentioned here were fixed in 4335e2fb34050dd66bd03c9b22923c770f3a35ea and #2

**Comment by KevinWorkman** [comment]
Confirmed. Also seems to work in all other browsers.

Awesome work. It's really cool to see other people participating. Thanks a lot!

If I ever get Happy Coding t-shirts made, you're getting a free one. :smile_cat:

**Comment by bigbass1997** [comment]
Sounds good to me, just hope such t-shirt comes in a good size...

**Comment by bigbass1997** [comment]
Discovered a new but related problem..

During the initial load of the page, if you try to set the src attribute using JS before the img tag, the img tag's src attribute will be set to whatever it is in the HTML tag and not what JS tells it to be.

So what's happening is if your theme cookie is set for dark theme, the page loads, running the JS script first, then `<img id="github-img" src="/images/GitHub-Mark-32px.png">`. The attribute for that img will be just that, instead of what's set in JS. Now once you press the change theme button, since you are not reloading the entire page, it runs the JS after such img tag has been "created"/placed.

This problem only happens when the user changes to the dark theme and then at some point reloads the page or loads any other page on the site; because the "default" image (what's set in HTML, not JS), is the normal/black Github image.

Note that not setting the HTML img tag's src attribute at all, does not fix the problem. In fact, instead of seeing the default image when loading either themes, no image will be rendered.

## 

If the same strategy is to be used to set that image based on the theme through JS, I assume the JS will have to be run after the img tag is "created"/placed in the document. Unless there is a workaround that I do not know.

**Comment by KevinWorkman** [comment]
You're exactly right. The JavaScript is firing before the page has been loaded, so there is no `img` to change the `src` on.

To fix this, I've separated the image logic into its own function called `doImageButtons` (I might add more buttons later, dunno), then just call that as soon as the page is loaded (which is simply `$(doImageButtons)` using JQuery).

This seems to work okay so I'm going to close the issue, but let me know if you notice any other problems. This has been really helpful.

This fix does have the slightly annoying issue of causing a slight flicker when the page is loaded. That might be a bigger deal if we have more images. That's a "nice to have" fix, not a "need to have" fix.
