### ISSUE TITLE
New Google Cloud Platform setup instructions and setup

### ISSUE THREAD

**Issue by KevinWorkman** [KevinWorkman/HappyCoding#17]
Google Cloud Platform is based on having projects, and then setting up services in those projects.

I already use Google Cloud Platform for a couple things, so my account is already set up.

I need a list of steps that a brand new person needs to follow to set up a project and get App Engine and Cloud SQL services set up.

This is mostly for the databases tutorial: http://happycoding.io/tutorials/java-server/databases

**Comment by humblelad** [comment]
I believe all such info is given in cloud.google.com (https://cloud.google.com/sql/docs/mysql/connect-app-engine, https://cloud.google.com/sql/docs/mysql/quickstart etc) .
