### ISSUE TITLE
Unable to signup to the forum

### ISSUE THREAD

**Issue by humblelad** [KevinWorkman/HappyCoding#26]
I was trying to signup to forum via github signup but it is unable it do so("sorry, there was an error authorising your account"). On a further look, I see that forum.happycoding.io is running on top of http and shows "not secure"

**Comment by KevinWorkman** [comment]
Hey thanks for the report. I think there two separate things happening:

1. forum.happycoding.io was 99% https, the only exception being the background image. That was enough to display a warning in chrome, but I don't think it would have blocked you from registering via GitHub. In any case, this is fixed now, thank you for pointing it out.

2. I believe [this](https://meta.discourse.org/t/github-logins-using-deprecated-authentication-api/140566) was causing the problem registering via GitHub. I've upgraded the forum to the latest version of Discourse, and I've double-checked my GitHub authorization settings.

I don't have a great way to test this on my end, so do you mind trying again?

**Comment by humblelad** [comment]
Great. Now it is working. Thanks for looking into it!
