### ISSUE TITLE
Create prettier thumbnails

### ISSUE THREAD

**Issue by KevinWorkman** [KevinWorkman/HappyCoding#4]
Right now a lot of the tutorial link boxes just use stretched versions of images found inside that tutorial. To fix this, we need to go through each tutorial and create a pretty 200x100 thumbnail them.

**Comment by humblelad** [comment]
You mean this has to be done manually ?

**Comment by KevinWorkman** [comment]
Yeah pretty much. I was actually going to take a look at this in the near future, but if you're interested: basically you'd "just" need to run the code in the tutorials and create a nice(r)-looking 200x100 thumbnail from it.

**Comment by KevinWorkman** [comment]
I've been updating the thumbnails as I've rewritten a lot of the tutorials, at least for Processing which had the worst thumbnails.

I think there's still some work to do, e.g. I think I prefer still images over animated thumbnails. But I don't think this is worth anybody else thinking too hard about it, so I'm going to close this out.
